# -*- coding: utf-8 -*-
"""Primeiro exemplo em Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UWI1LpLaTEFC-0Q7Nn5oeOsJY21RFylT

Primeiro exemplo em Python
**Jhonathan Henrique**
"""

# Primeiro exemplo em Python
print("Hello World!")

# Comando de entrada, pergunto o nome e armazeno este nome na variável
nome = input("Informe seu nome: ")

# Programa dirá Olá informando o nome do usuário!
print(f"Olá, {nome}")