# -*- coding: utf-8 -*-
"""Python (Dicionario).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8kWd6p4fXoLkKy1_W3FsDeh21Ds5JJ_
"""

#Criar um dicionario de dados
produto = {
    "nome": "SmartTV LG",
    "qtde": 10,
    "preco": 3999.90
}

print(produto)

#Se eu quiser saber a quantidade do produto presente no dicionario "Produto"
print(produto['qtde'])