# -*- coding: utf-8 -*-
"""Python (Array).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1koamj9c27oy6xst85uwzNWounAvW8pRH
"""

fruta = "morango"
print(fruta)

#Iniciar o arrays fruta informando o nome das frutas selecionadas..
frutas = ["laranja", "maçã", "Banana"]

#Exibir o conteudo do array frutas.
print(frutas)

#Exiba o nome da segunda fruta armazenada do array frutas
print(frutas[1])

#Quantas frutas temos no array frutas?
qtd_frutas = len(frutas)
print(qtd_frutas)