# -*- coding: utf-8 -*-
"""Python (lista de dicionario).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1grOX0dlQW5HEAaumVdP7LJvLrGqxu0OF
"""

#Lista de produtos
produtos = []

#Usuario vai digitar tres produtos de sua escolha informando nome, quantidade e preço
num = 1
while (num <=3):
  nome = input(f"Informe o nome do {num}o. produto: ")
  qtde = int(input(f"Informe a quantidade do {num}o. produto: "))
  preco = float(input(f"Digite o preço do {num}o. produto: "))
  produto = {
      "nome": nome,
      "qtde": qtde,
      "preco": preco
  }
  produtos.append(produto)
  num = num +1

  print(produtos)