# -*- coding: utf-8 -*-
"""Segundo exemplo em Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VOLuJKiYelGt8vBuIdHsNvfZ7XAfc7qw
"""

# Começa perguntando o nome do produto, quantidade em estoque e seu preço.
nome = input("Informe o nome do produto: ")
qtde = int(input("Digite a quantidade deste produto no estoque: "))
preco = float(input("Digite o preço deste produto: "))

print(f"Nome do Produto: {nome}")
print(f"Quantidade disponivel: {qtde}")
print(f"Preço por unidade: {preco}")